@startuml
title Proxy SDK
autonumber

box "MOSIP" #LightBlue
participant "MOSIP server" as MS
participant "Client application" as CA
end box

box "MOSIP" #LightBlue
participant "Proxy SDK Methods" as SDK
participant "Proxy SDK Services" as SDKS
end box

== Initialization ==
CA -> SDK: Init
activate SDK

SDK -> SDKS: Initialization API
activate SDKS

SDKS -> MS: Acquire token using clientid and secret key
activate MS
return **headers**: Token {**T1**}

return **headers**: Token {**T1**}\n**body**: API response {success/failure}

return Response {success/failure} & **T1**

CA -> MS: Validate token **T1** with server
CA -> CA: Validation {success/failure}
'alt if Validation is successful
'CA <- CA: Save the token in encrypted db (say **stored SDK token**) for offline validation
'else if Validation fails
'CA <- CA: do nothing
'end

== Match Request ==
CA -> SDK: Match biometrics B1 with a given gallery
activate SDK

SDK -> SDKS: Match API {signature will be same a match\nmethods but as json string}
activate SDKS
return **headers**: Token {**T1**}\n**body**: match response

return **headers**: Token {**T1**}\n**body**: API response {Match decision}

alt if Token {**T1**} validated successful
CA <- CA: Accept the result and proceed further
else if Token {**T1**} validation fails
CA <- CA: Throw SDK validation error
end

@enduml