@startuml
title Proxy SDK

(*) --> "CA calls for **status check**.\nCA fetches **T1** from SDK"
note left
**CA** - Client Application
**Stored SDK token** - token saved
by CA in local database
**T1** - Token stored in SDK
end note
If "System is online" then
--> [true] "Validate the token {**T1**} with server (keycloak)"
    If "Validation success" then
    --> [true] "Token verified, match request can\nbe sent now"
    else
    --> [false] "CA calls for **Initialization**"
    endif
else
--> [false] "Validate the token {**T1**} with **stored SDK token**"

If "Validation success" then
--> [true] "Token verified, match request can\nbe sent now"
else
--> [false] "CA calls for **Initialization**"
endif

If "System is online" then
--> [true] "Token created, match request can\nbe sent now"
else
--> [false] "Show alert to user **''system should be online for Initialization''**"
endif

endif

@enduml